// Codegen — o código gerado a partir dos schemas FlatBuffers, e a baseline do
// PHPStan que cobre o que ele emite.
//
// Um arquivo por assunto:
//
//	main.go       o tipo, as constantes e esta explicação
//	flatc.go      instalar o compilador
//	fbsphp.go     gerar e normalizar o PHP
//	fbsgo.go      gerar os bindings Go
//	fbscheck.go   conferir se os bindings commitados estão em dia
//	baseline.go   reconstruir a baseline do PHPStan
//
// ---------------------------------------------------------------------------
// Aqui não há script envelopado: a lógica FOI REESCRITA.
//
// O que existia em back/scripts/ e virou Go:
//
//	generate-flatbuffers.php        invocava o flatc resolvendo caminhos em PHP,
//	                                porque `$(pwd)` e glob de shell não rodavam
//	                                no Windows. Num container Linux essa razão
//	                                deixou de existir.
//	patch-flatbuffers.php           as transformações sobre o PHP emitido pelo
//	                                flatc — em fbsphp.go, uma a uma, com o
//	                                motivo de cada junto.
//	generate-flatbuffers-go.sh      flatc mais dois `perl -i`.
//	generate-phpstan-baseline.php   análise, filtro e emissão do NEON — em
//	                                baseline.go.
//
// As transformações de texto rodam em Go, sobre o conteúdo do Directory, e não
// dentro do container: são substituição de string e parsing de JSON, não
// precisam de PHP para acontecer.
//
// R6.1 — nenhuma função escreve no repositório. Todas devolvem Directory ou
// File, e quem grava é o `export` de quem chamou.
// ---------------------------------------------------------------------------
package main

// A mesma versão usada em .github/workflows/ci.yml e no front. O binário
// oficial da release evita compilar o FlatBuffers inteiro só para gerar
// bindings.
const flatcVersion = "25.12.19"

// Só arquivos com este cabeçalho são tocados. É o que separa as tabelas que o
// flatc emite dos proxies e contratos escritos à mão, que ficam intactos.
const flatcHeader = "automatically generated by the FlatBuffers compiler"

type Codegen struct{}
