<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Metrics;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class MetricsResponse extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return MetricsResponse
     */
    public static function getRootAsMetricsResponse(ByteBuffer $bb)
    {
        $obj = new MetricsResponse();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return MetricsResponse
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function getActiveContainers()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return int
     */
    public function getTotalContainers()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return float
     */
    public function getYardLoad()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return int
     */
    public function getRegisteredProducts()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    public function getOccupancyDivision()
    {
        $obj = new OccupancyDivision();
        $o = $this->__offset(12);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : null;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startMetricsResponse(FlatbufferBuilder $builder)
    {
        $builder->StartObject(5);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createMetricsResponse(FlatbufferBuilder $builder, $active_containers, $total_containers, $yard_load, $registered_products, $occupancy_division)
    {
        $builder->startObject(5);
        self::addActiveContainers($builder, $active_containers);
        self::addTotalContainers($builder, $total_containers);
        self::addYardLoad($builder, $yard_load);
        self::addRegisteredProducts($builder, $registered_products);
        self::addOccupancyDivision($builder, $occupancy_division);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addActiveContainers(FlatbufferBuilder $builder, $activeContainers)
    {
        $builder->addIntX(0, $activeContainers, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addTotalContainers(FlatbufferBuilder $builder, $totalContainers)
    {
        $builder->addIntX(1, $totalContainers, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addYardLoad(FlatbufferBuilder $builder, $yardLoad)
    {
        $builder->addDoubleX(2, $yardLoad, 0.0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addRegisteredProducts(FlatbufferBuilder $builder, $registeredProducts)
    {
        $builder->addIntX(3, $registeredProducts, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addOccupancyDivision(FlatbufferBuilder $builder, $occupancyDivision)
    {
        $builder->addOffsetX(4, $occupancyDivision, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endMetricsResponse(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
