<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Metrics;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class OccupancyDivision extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return OccupancyDivision
     */
    public static function getRootAsOccupancyDivision(ByteBuffer $bb)
    {
        $obj = new OccupancyDivision();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return OccupancyDivision
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function getEmpty()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return int
     */
    public function getLoading()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return int
     */
    public function getSealed()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return int
     */
    public function getInTransit()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startOccupancyDivision(FlatbufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createOccupancyDivision(FlatbufferBuilder $builder, $empty, $loading, $sealed, $in_transit)
    {
        $builder->startObject(4);
        self::addEmpty($builder, $empty);
        self::addLoading($builder, $loading);
        self::addSealed($builder, $sealed);
        self::addInTransit($builder, $in_transit);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addEmpty(FlatbufferBuilder $builder, $empty)
    {
        $builder->addIntX(0, $empty, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addLoading(FlatbufferBuilder $builder, $loading)
    {
        $builder->addIntX(1, $loading, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addSealed(FlatbufferBuilder $builder, $sealed)
    {
        $builder->addIntX(2, $sealed, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addInTransit(FlatbufferBuilder $builder, $inTransit)
    {
        $builder->addIntX(3, $inTransit, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endOccupancyDivision(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
