<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Manifest;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class ManifestResponse extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ManifestResponse
     */
    public static function getRootAsManifestResponse(ByteBuffer $bb)
    {
        $obj = new ManifestResponse();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ManifestResponse
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getMessage(): ?string
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getContainer()
    {
        $obj = new ContainerResponse();
        $o = $this->__offset(6);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : null;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startManifestResponse(FlatbufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createManifestResponse(FlatbufferBuilder $builder, $message, $container)
    {
        $builder->startObject(2);
        self::addMessage($builder, $message);
        self::addContainer($builder, $container);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addMessage(FlatbufferBuilder $builder, $message)
    {
        $builder->addOffsetX(0, $message, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addContainer(FlatbufferBuilder $builder, $container)
    {
        $builder->addOffsetX(1, $container, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endManifestResponse(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
