<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Manifest;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class UnloadItemRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return UnloadItemRequest
     */
    public static function getRootAsUnloadItemRequest(ByteBuffer $bb)
    {
        $obj = new UnloadItemRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return UnloadItemRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function getContainerId()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return int
     */
    public function getProductId()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return double
     */
    public function getQuantity()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startUnloadItemRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(3);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return UnloadItemRequest
     */
    public static function createUnloadItemRequest(FlatBufferBuilder $builder, $container_id, $product_id, $quantity)
    {
        $builder->startObject(3);
        self::addContainerId($builder, $container_id);
        self::addProductId($builder, $product_id);
        self::addQuantity($builder, $quantity);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addContainerId(FlatBufferBuilder $builder, $containerId)
    {
        $builder->addIntX(0, $containerId, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addProductId(FlatBufferBuilder $builder, $productId)
    {
        $builder->addIntX(1, $productId, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addQuantity(FlatBufferBuilder $builder, $quantity)
    {
        $builder->addDoubleX(2, $quantity, 0.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endUnloadItemRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
