<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Server;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class ProjectInfo extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ProjectInfo
     */
    public static function getRootAsProjectInfo(ByteBuffer $bb)
    {
        $obj = new ProjectInfo();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ProjectInfo
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getName(): ?string
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getVersion(): ?string
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getEnvironment(): ?string
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getRuntime(): ?string
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return float
     */
    public function getMemoryUsageMb()
    {
        $o = $this->__offset(12);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startProjectInfo(FlatbufferBuilder $builder)
    {
        $builder->StartObject(5);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createProjectInfo(FlatbufferBuilder $builder, $name, $version, $environment, $runtime, $memory_usage_mb)
    {
        $builder->startObject(5);
        self::addName($builder, $name);
        self::addVersion($builder, $version);
        self::addEnvironment($builder, $environment);
        self::addRuntime($builder, $runtime);
        self::addMemoryUsageMb($builder, $memory_usage_mb);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatbufferBuilder $builder, $name)
    {
        $builder->addOffsetX(0, $name, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addVersion(FlatbufferBuilder $builder, $version)
    {
        $builder->addOffsetX(1, $version, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addEnvironment(FlatbufferBuilder $builder, $environment)
    {
        $builder->addOffsetX(2, $environment, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addRuntime(FlatbufferBuilder $builder, $runtime)
    {
        $builder->addOffsetX(3, $runtime, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addMemoryUsageMb(FlatbufferBuilder $builder, $memoryUsageMb)
    {
        $builder->addDoubleX(4, $memoryUsageMb, 0.0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endProjectInfo(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
