<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Container;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class ContainerResponse extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ContainerResponse
     */
    public static function getRootAsContainerResponse(ByteBuffer $bb)
    {
        $obj = new ContainerResponse();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ContainerResponse
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function getId()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    public function getCode()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return double
     */
    public function getCurrentWeight()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return double
     */
    public function getMaxCapacity()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return byte
     */
    public function getStatus()
    {
        $o = $this->__offset(12);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : \API\Fbs\Common\ContainerStatus::Empty;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startContainerResponse(FlatBufferBuilder $builder)
    {
        $builder->StartObject(5);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ContainerResponse
     */
    public static function createContainerResponse(FlatBufferBuilder $builder, $id, $code, $current_weight, $max_capacity, $status)
    {
        $builder->startObject(5);
        self::addId($builder, $id);
        self::addCode($builder, $code);
        self::addCurrentWeight($builder, $current_weight);
        self::addMaxCapacity($builder, $max_capacity);
        self::addStatus($builder, $status);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addId(FlatBufferBuilder $builder, $id)
    {
        $builder->addIntX(0, $id, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addCode(FlatBufferBuilder $builder, $code)
    {
        $builder->addOffsetX(1, $code, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addCurrentWeight(FlatBufferBuilder $builder, $currentWeight)
    {
        $builder->addDoubleX(2, $currentWeight, 0.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addMaxCapacity(FlatBufferBuilder $builder, $maxCapacity)
    {
        $builder->addDoubleX(3, $maxCapacity, 0.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addStatus(FlatBufferBuilder $builder, $status)
    {
        $builder->addByteX(4, $status, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endContainerResponse(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
