<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Container;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class ContainerUpdateRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ContainerUpdateRequest
     */
    public static function getRootAsContainerUpdateRequest(ByteBuffer $bb)
    {
        $obj = new ContainerUpdateRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ContainerUpdateRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return float
     */
    public function getMaxCapacity()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startContainerUpdateRequest(FlatbufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createContainerUpdateRequest(FlatbufferBuilder $builder, $max_capacity)
    {
        $builder->startObject(1);
        self::addMaxCapacity($builder, $max_capacity);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addMaxCapacity(FlatbufferBuilder $builder, $maxCapacity)
    {
        $builder->addDoubleX(0, $maxCapacity, 0.0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endContainerUpdateRequest(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
