<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Container;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class ContainerSummaryResponse extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ContainerSummaryResponse
     */
    public static function getRootAsContainerSummaryResponse(ByteBuffer $bb)
    {
        $obj = new ContainerSummaryResponse();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ContainerSummaryResponse
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getContainer()
    {
        $obj = new ContainerResponse();
        $o = $this->__offset(4);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : null;
    }

    /**
     * @returnVectorOffset
     */
    public function getManifest($j)
    {
        $o = $this->__offset(6);
        $obj = new CargoManifestItem();
        return $o != 0 ? $obj->init($this->__indirect($this->__vector($o) + $j * 4), $this->bb) : null;
    }

    /**
     * @return int
     */
    public function getManifestLength()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @returnVectorOffset
     */
    public function getRecentLogs($j)
    {
        $o = $this->__offset(8);
        $obj = new TelemetryLogItem();
        return $o != 0 ? $obj->init($this->__indirect($this->__vector($o) + $j * 4), $this->bb) : null;
    }

    /**
     * @return int
     */
    public function getRecentLogsLength()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startContainerSummaryResponse(FlatbufferBuilder $builder)
    {
        $builder->StartObject(3);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createContainerSummaryResponse(FlatbufferBuilder $builder, $container, $manifest, $recent_logs)
    {
        $builder->startObject(3);
        self::addContainer($builder, $container);
        self::addManifest($builder, $manifest);
        self::addRecentLogs($builder, $recent_logs);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addContainer(FlatbufferBuilder $builder, $container)
    {
        $builder->addOffsetX(0, $container, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addManifest(FlatbufferBuilder $builder, $manifest)
    {
        $builder->addOffsetX(1, $manifest, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createManifestVector(FlatbufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startManifestVector(FlatbufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addRecentLogs(FlatbufferBuilder $builder, $recentLogs)
    {
        $builder->addOffsetX(2, $recentLogs, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createRecentLogsVector(FlatbufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startRecentLogsVector(FlatbufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endContainerSummaryResponse(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
