<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Container;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class TelemetryLogItem extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return TelemetryLogItem
     */
    public static function getRootAsTelemetryLogItem(ByteBuffer $bb)
    {
        $obj = new TelemetryLogItem();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return TelemetryLogItem
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getId(): ?string
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getEvent(): ?string
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getDescription(): ?string
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getTimestamp(): ?string
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startTelemetryLogItem(FlatbufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createTelemetryLogItem(FlatbufferBuilder $builder, $id, $event, $description, $timestamp)
    {
        $builder->startObject(4);
        self::addId($builder, $id);
        self::addEvent($builder, $event);
        self::addDescription($builder, $description);
        self::addTimestamp($builder, $timestamp);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addId(FlatbufferBuilder $builder, $id)
    {
        $builder->addOffsetX(0, $id, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addEvent(FlatbufferBuilder $builder, $event)
    {
        $builder->addOffsetX(1, $event, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addDescription(FlatbufferBuilder $builder, $description)
    {
        $builder->addOffsetX(2, $description, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addTimestamp(FlatbufferBuilder $builder, $timestamp)
    {
        $builder->addOffsetX(3, $timestamp, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endTelemetryLogItem(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
