<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Container;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class TelemetryLogItem extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return TelemetryLogItem
     */
    public static function getRootAsTelemetryLogItem(ByteBuffer $bb)
    {
        $obj = new TelemetryLogItem();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return TelemetryLogItem
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function getId()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getEvent()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : \API\Fbs\Common\TelemetryEvent::Create;
    }

    public function getDescription()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getTimestamp()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startTelemetryLogItem(FlatBufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return TelemetryLogItem
     */
    public static function createTelemetryLogItem(FlatBufferBuilder $builder, $id, $event, $description, $timestamp)
    {
        $builder->startObject(4);
        self::addId($builder, $id);
        self::addEvent($builder, $event);
        self::addDescription($builder, $description);
        self::addTimestamp($builder, $timestamp);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addId(FlatBufferBuilder $builder, $id)
    {
        $builder->addIntX(0, $id, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addEvent(FlatBufferBuilder $builder, $event)
    {
        $builder->addByteX(1, $event, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addDescription(FlatBufferBuilder $builder, $description)
    {
        $builder->addOffsetX(2, $description, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addTimestamp(FlatBufferBuilder $builder, $timestamp)
    {
        $builder->addOffsetX(3, $timestamp, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endTelemetryLogItem(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
