<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Account;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class AccountProfileResponse extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return AccountProfileResponse
     */
    public static function getRootAsAccountProfileResponse(ByteBuffer $bb)
    {
        $obj = new AccountProfileResponse();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return AccountProfileResponse
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getId(): ?string
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getName(): ?string
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getEmail(): ?string
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @returnVectorOffset
     */
    public function getRoles($j)
    {
        $o = $this->__offset(10);
        $obj = new RoleResponse();
        return $o != 0 ? $obj->init($this->__indirect($this->__vector($o) + $j * 4), $this->bb) : null;
    }

    /**
     * @return int
     */
    public function getRolesLength()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startAccountProfileResponse(FlatbufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createAccountProfileResponse(FlatbufferBuilder $builder, $id, $name, $email, $roles)
    {
        $builder->startObject(4);
        self::addId($builder, $id);
        self::addName($builder, $name);
        self::addEmail($builder, $email);
        self::addRoles($builder, $roles);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addId(FlatbufferBuilder $builder, $id)
    {
        $builder->addOffsetX(0, $id, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatbufferBuilder $builder, $name)
    {
        $builder->addOffsetX(1, $name, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addEmail(FlatbufferBuilder $builder, $email)
    {
        $builder->addOffsetX(2, $email, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addRoles(FlatbufferBuilder $builder, $roles)
    {
        $builder->addOffsetX(3, $roles, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createRolesVector(FlatbufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startRolesVector(FlatbufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endAccountProfileResponse(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
