<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Account;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class AccountUpdateRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return AccountUpdateRequest
     */
    public static function getRootAsAccountUpdateRequest(ByteBuffer $bb)
    {
        $obj = new AccountUpdateRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return AccountUpdateRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getName()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getEmail()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startAccountUpdateRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return AccountUpdateRequest
     */
    public static function createAccountUpdateRequest(FlatBufferBuilder $builder, $name, $email)
    {
        $builder->startObject(2);
        self::addName($builder, $name);
        self::addEmail($builder, $email);
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        $builder->required($o, 6);  // email
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatBufferBuilder $builder, $name)
    {
        $builder->addOffsetX(0, $name, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addEmail(FlatBufferBuilder $builder, $email)
    {
        $builder->addOffsetX(1, $email, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endAccountUpdateRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        $builder->required($o, 6);  // email
        return $o;
    }
}
