<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Account;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class AccountPasswordChangeRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return AccountPasswordChangeRequest
     */
    public static function getRootAsAccountPasswordChangeRequest(ByteBuffer $bb)
    {
        $obj = new AccountPasswordChangeRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return AccountPasswordChangeRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getCurrentPassword()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getNewPassword()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startAccountPasswordChangeRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return AccountPasswordChangeRequest
     */
    public static function createAccountPasswordChangeRequest(FlatBufferBuilder $builder, $current_password, $new_password)
    {
        $builder->startObject(2);
        self::addCurrentPassword($builder, $current_password);
        self::addNewPassword($builder, $new_password);
        $o = $builder->endObject();
        $builder->required($o, 4);  // current_password
        $builder->required($o, 6);  // new_password
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addCurrentPassword(FlatBufferBuilder $builder, $currentPassword)
    {
        $builder->addOffsetX(0, $currentPassword, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addNewPassword(FlatBufferBuilder $builder, $newPassword)
    {
        $builder->addOffsetX(1, $newPassword, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endAccountPasswordChangeRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // current_password
        $builder->required($o, 6);  // new_password
        return $o;
    }
}
