<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Product;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class ProductResponse extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ProductResponse
     */
    public static function getRootAsProductResponse(ByteBuffer $bb)
    {
        $obj = new ProductResponse();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ProductResponse
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getId(): ?string
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getName(): ?string
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return float
     */
    public function getDensity()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return int
     */
    public function getRiskClass()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : \API\Fbs\Common\RiskClass::Class1Explosives;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startProductResponse(FlatbufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createProductResponse(FlatbufferBuilder $builder, $id, $name, $density, $risk_class)
    {
        $builder->startObject(4);
        self::addId($builder, $id);
        self::addName($builder, $name);
        self::addDensity($builder, $density);
        self::addRiskClass($builder, $risk_class);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addId(FlatbufferBuilder $builder, $id)
    {
        $builder->addOffsetX(0, $id, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatbufferBuilder $builder, $name)
    {
        $builder->addOffsetX(1, $name, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addDensity(FlatbufferBuilder $builder, $density)
    {
        $builder->addDoubleX(2, $density, 0.0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addRiskClass(FlatbufferBuilder $builder, $riskClass)
    {
        $builder->addByteX(3, $riskClass, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endProductResponse(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
