<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Product;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class ProductCreateRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ProductCreateRequest
     */
    public static function getRootAsProductCreateRequest(ByteBuffer $bb)
    {
        $obj = new ProductCreateRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ProductCreateRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getName()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return double
     */
    public function getDensity()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getDouble($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return byte
     */
    public function getRiskClass()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : \API\Fbs\Common\RiskClass::Class1Explosives;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startProductCreateRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(3);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ProductCreateRequest
     */
    public static function createProductCreateRequest(FlatBufferBuilder $builder, $name, $density, $risk_class)
    {
        $builder->startObject(3);
        self::addName($builder, $name);
        self::addDensity($builder, $density);
        self::addRiskClass($builder, $risk_class);
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatBufferBuilder $builder, $name)
    {
        $builder->addOffsetX(0, $name, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param double
     * @return void
     */
    public static function addDensity(FlatBufferBuilder $builder, $density)
    {
        $builder->addDoubleX(1, $density, 0.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addRiskClass(FlatBufferBuilder $builder, $riskClass)
    {
        $builder->addByteX(2, $riskClass, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endProductCreateRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        return $o;
    }
}
