<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Common;

class ContainerStatus
{
    const Empty = 0;
    const Loading = 1;
    const Sealed = 2;
    const InTransit = 3;

    private static $names = array(
        ContainerStatus::Empty=>"Empty",
        ContainerStatus::Loading=>"Loading",
        ContainerStatus::Sealed=>"Sealed",
        ContainerStatus::InTransit=>"InTransit",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
