<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Common;

class Permission
{
    const ProductRead = 0;
    const ProductCreate = 1;
    const ProductUpdate = 2;
    const ProductDelete = 3;
    const ContainerRead = 4;
    const ContainerCreate = 5;
    const ContainerUpdate = 6;
    const ContainerDelete = 7;
    const ContainerSeal = 8;
    const ContainerDispatch = 9;
    const ContainerSummary = 10;
    const ManifestLoad = 11;
    const ManifestUnload = 12;
    const UserGet = 13;
    const UserList = 14;
    const UserCreate = 15;
    const UserUpdate = 16;
    const UserDelete = 17;
    const UserChangePassword = 18;
    const UserUpdateRoles = 19;
    const RoleList = 20;
    const RoleCreate = 21;
    const RoleUpdatePermissions = 22;
    const MetricsRead = 23;

    private static $names = array(
        Permission::ProductRead=>"ProductRead",
        Permission::ProductCreate=>"ProductCreate",
        Permission::ProductUpdate=>"ProductUpdate",
        Permission::ProductDelete=>"ProductDelete",
        Permission::ContainerRead=>"ContainerRead",
        Permission::ContainerCreate=>"ContainerCreate",
        Permission::ContainerUpdate=>"ContainerUpdate",
        Permission::ContainerDelete=>"ContainerDelete",
        Permission::ContainerSeal=>"ContainerSeal",
        Permission::ContainerDispatch=>"ContainerDispatch",
        Permission::ContainerSummary=>"ContainerSummary",
        Permission::ManifestLoad=>"ManifestLoad",
        Permission::ManifestUnload=>"ManifestUnload",
        Permission::UserGet=>"UserGet",
        Permission::UserList=>"UserList",
        Permission::UserCreate=>"UserCreate",
        Permission::UserUpdate=>"UserUpdate",
        Permission::UserDelete=>"UserDelete",
        Permission::UserChangePassword=>"UserChangePassword",
        Permission::UserUpdateRoles=>"UserUpdateRoles",
        Permission::RoleList=>"RoleList",
        Permission::RoleCreate=>"RoleCreate",
        Permission::RoleUpdatePermissions=>"RoleUpdatePermissions",
        Permission::MetricsRead=>"MetricsRead",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
