<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Common;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class ProblemDetails extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ProblemDetails
     */
    public static function getRootAsProblemDetails(ByteBuffer $bb)
    {
        $obj = new ProblemDetails();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ProblemDetails
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getType()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getTitle()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    public function getDetail()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getInstance()
    {
        $o = $this->__offset(12);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startProblemDetails(FlatBufferBuilder $builder)
    {
        $builder->StartObject(5);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ProblemDetails
     */
    public static function createProblemDetails(FlatBufferBuilder $builder, $type, $title, $status, $detail, $instance)
    {
        $builder->startObject(5);
        self::addType($builder, $type);
        self::addTitle($builder, $title);
        self::addStatus($builder, $status);
        self::addDetail($builder, $detail);
        self::addInstance($builder, $instance);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addType(FlatBufferBuilder $builder, $type)
    {
        $builder->addOffsetX(0, $type, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addTitle(FlatBufferBuilder $builder, $title)
    {
        $builder->addOffsetX(1, $title, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addStatus(FlatBufferBuilder $builder, $status)
    {
        $builder->addIntX(2, $status, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addDetail(FlatBufferBuilder $builder, $detail)
    {
        $builder->addOffsetX(3, $detail, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addInstance(FlatBufferBuilder $builder, $instance)
    {
        $builder->addOffsetX(4, $instance, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endProblemDetails(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
