<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Common;

class RiskClass
{
    const Class1Explosives = 0;
    const Class2Gases = 1;
    const Class3FlammableLiquids = 2;
    const Class4FlammableSolids = 3;
    const Class5OxidizingSubstances = 4;
    const Class6ToxicSubstances = 5;
    const Class7RadioactiveMaterials = 6;
    const Class8CorrosiveSubstances = 7;
    const Class9Miscellaneous = 8;
    const None = 9;

    private static $names = array(
        RiskClass::Class1Explosives=>"Class1Explosives",
        RiskClass::Class2Gases=>"Class2Gases",
        RiskClass::Class3FlammableLiquids=>"Class3FlammableLiquids",
        RiskClass::Class4FlammableSolids=>"Class4FlammableSolids",
        RiskClass::Class5OxidizingSubstances=>"Class5OxidizingSubstances",
        RiskClass::Class6ToxicSubstances=>"Class6ToxicSubstances",
        RiskClass::Class7RadioactiveMaterials=>"Class7RadioactiveMaterials",
        RiskClass::Class8CorrosiveSubstances=>"Class8CorrosiveSubstances",
        RiskClass::Class9Miscellaneous=>"Class9Miscellaneous",
        RiskClass::None=>"None",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
