<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Common;

class TelemetryEvent
{
    const Create = 0;
    const Load = 1;
    const Unload = 2;
    const Seal = 3;
    const Dispatch = 4;

    private static $names = array(
        TelemetryEvent::Create=>"Create",
        TelemetryEvent::Load=>"Load",
        TelemetryEvent::Unload=>"Unload",
        TelemetryEvent::Seal=>"Seal",
        TelemetryEvent::Dispatch=>"Dispatch",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
