<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Common;

class TelemetryEvent
{
    const Load = 0;
    const Unload = 1;

    private static $names = array(
        TelemetryEvent::Load=>"Load",
        TelemetryEvent::Unload=>"Unload",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
