<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Metadata;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class MetadataItemResponse extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return MetadataItemResponse
     */
    public static function getRootAsMetadataItemResponse(ByteBuffer $bb)
    {
        $obj = new MetadataItemResponse();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return MetadataItemResponse
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return int
     */
    public function getId()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    public function getSlug(): ?string
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startMetadataItemResponse(FlatbufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createMetadataItemResponse(FlatbufferBuilder $builder, $id, $slug)
    {
        $builder->startObject(2);
        self::addId($builder, $id);
        self::addSlug($builder, $slug);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addId(FlatbufferBuilder $builder, $id)
    {
        $builder->addIntX(0, $id, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addSlug(FlatbufferBuilder $builder, $slug)
    {
        $builder->addOffsetX(1, $slug, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endMetadataItemResponse(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
