<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Admin;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class RolePermissionsUpdateRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RolePermissionsUpdateRequest
     */
    public static function getRootAsRolePermissionsUpdateRequest(ByteBuffer $bb)
    {
        $obj = new RolePermissionsUpdateRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RolePermissionsUpdateRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @param int offset
     * @return string
     */
    public function getPermissions($j)
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($this->__vector($o) + $j * 4) : 0;
    }

    /**
     * @return int
     */
    public function getPermissionsLength()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startRolePermissionsUpdateRequest(FlatbufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createRolePermissionsUpdateRequest(FlatbufferBuilder $builder, $permissions)
    {
        $builder->startObject(1);
        self::addPermissions($builder, $permissions);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addPermissions(FlatbufferBuilder $builder, $permissions)
    {
        $builder->addOffsetX(0, $permissions, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createPermissionsVector(FlatbufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startPermissionsVector(FlatbufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endRolePermissionsUpdateRequest(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
