<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Admin;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RoleCreateRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RoleCreateRequest
     */
    public static function getRootAsRoleCreateRequest(ByteBuffer $bb)
    {
        $obj = new RoleCreateRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RoleCreateRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getName()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param int offset
     * @return byte
     */
    public function getPermissions($j)
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getByte($this->__vector($o) + $j * 1) : \API\Fbs\Common\Permission::ProductRead;
    }

    /**
     * @return int
     */
    public function getPermissionsLength()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @return string
     */
    public function getPermissionsBytes()
    {
        return $this->__vector_as_bytes(6);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startRoleCreateRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return RoleCreateRequest
     */
    public static function createRoleCreateRequest(FlatBufferBuilder $builder, $name, $permissions)
    {
        $builder->startObject(2);
        self::addName($builder, $name);
        self::addPermissions($builder, $permissions);
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatBufferBuilder $builder, $name)
    {
        $builder->addOffsetX(0, $name, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addPermissions(FlatBufferBuilder $builder, $permissions)
    {
        $builder->addOffsetX(1, $permissions, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createPermissionsVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(1, count($data), 1);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putByte($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startPermissionsVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(1, $numElems, 1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endRoleCreateRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        return $o;
    }
}
