<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Admin;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class UserRolesUpdateRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return UserRolesUpdateRequest
     */
    public static function getRootAsUserRolesUpdateRequest(ByteBuffer $bb)
    {
        $obj = new UserRolesUpdateRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return UserRolesUpdateRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @param int offset
     * @return string
     */
    public function getRoleIds($j)
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($this->__vector($o) + $j * 4) : 0;
    }

    /**
     * @return int
     */
    public function getRoleIdsLength()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startUserRolesUpdateRequest(FlatbufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createUserRolesUpdateRequest(FlatbufferBuilder $builder, $role_ids)
    {
        $builder->startObject(1);
        self::addRoleIds($builder, $role_ids);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addRoleIds(FlatbufferBuilder $builder, $roleIds)
    {
        $builder->addOffsetX(0, $roleIds, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createRoleIdsVector(FlatbufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startRoleIdsVector(FlatbufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endUserRolesUpdateRequest(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
