<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Admin;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class UserAdminPasswordResetRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return UserAdminPasswordResetRequest
     */
    public static function getRootAsUserAdminPasswordResetRequest(ByteBuffer $bb)
    {
        $obj = new UserAdminPasswordResetRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return UserAdminPasswordResetRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getNewPassword()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startUserAdminPasswordResetRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return UserAdminPasswordResetRequest
     */
    public static function createUserAdminPasswordResetRequest(FlatBufferBuilder $builder, $new_password)
    {
        $builder->startObject(1);
        self::addNewPassword($builder, $new_password);
        $o = $builder->endObject();
        $builder->required($o, 4);  // new_password
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addNewPassword(FlatBufferBuilder $builder, $newPassword)
    {
        $builder->addOffsetX(0, $newPassword, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endUserAdminPasswordResetRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // new_password
        return $o;
    }
}
