<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Admin;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class UserCreateRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return UserCreateRequest
     */
    public static function getRootAsUserCreateRequest(ByteBuffer $bb)
    {
        $obj = new UserCreateRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return UserCreateRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getName()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getEmail()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getInitialPassword()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param int offset
     * @return int
     */
    public function getRoleIds($j)
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getInt($this->__vector($o) + $j * 4) : 0;
    }

    /**
     * @return int
     */
    public function getRoleIdsLength()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startUserCreateRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return UserCreateRequest
     */
    public static function createUserCreateRequest(FlatBufferBuilder $builder, $name, $email, $initial_password, $role_ids)
    {
        $builder->startObject(4);
        self::addName($builder, $name);
        self::addEmail($builder, $email);
        self::addInitialPassword($builder, $initial_password);
        self::addRoleIds($builder, $role_ids);
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        $builder->required($o, 6);  // email
        $builder->required($o, 8);  // initial_password
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatBufferBuilder $builder, $name)
    {
        $builder->addOffsetX(0, $name, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addEmail(FlatBufferBuilder $builder, $email)
    {
        $builder->addOffsetX(1, $email, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addInitialPassword(FlatBufferBuilder $builder, $initialPassword)
    {
        $builder->addOffsetX(2, $initialPassword, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addRoleIds(FlatBufferBuilder $builder, $roleIds)
    {
        $builder->addOffsetX(3, $roleIds, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createRoleIdsVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putInt($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startRoleIdsVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endUserCreateRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        $builder->required($o, 6);  // email
        $builder->required($o, 8);  // initial_password
        return $o;
    }
}
