<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Auth;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class LoginRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return LoginRequest
     */
    public static function getRootAsLoginRequest(ByteBuffer $bb)
    {
        $obj = new LoginRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return LoginRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getEmail()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getPassword()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startLoginRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return LoginRequest
     */
    public static function createLoginRequest(FlatBufferBuilder $builder, $email, $password)
    {
        $builder->startObject(2);
        self::addEmail($builder, $email);
        self::addPassword($builder, $password);
        $o = $builder->endObject();
        $builder->required($o, 4);  // email
        $builder->required($o, 6);  // password
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addEmail(FlatBufferBuilder $builder, $email)
    {
        $builder->addOffsetX(0, $email, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addPassword(FlatBufferBuilder $builder, $password)
    {
        $builder->addOffsetX(1, $password, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endLoginRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // email
        $builder->required($o, 6);  // password
        return $o;
    }
}
