<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Auth;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class SetupRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return SetupRequest
     */
    public static function getRootAsSetupRequest(ByteBuffer $bb)
    {
        $obj = new SetupRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return SetupRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getName(): ?string
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getEmail(): ?string
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getPassword(): ?string
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startSetupRequest(FlatbufferBuilder $builder)
    {
        $builder->StartObject(3);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createSetupRequest(FlatbufferBuilder $builder, $name, $email, $password)
    {
        $builder->startObject(3);
        self::addName($builder, $name);
        self::addEmail($builder, $email);
        self::addPassword($builder, $password);
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        $builder->required($o, 6);  // email
        $builder->required($o, 8);  // password
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatbufferBuilder $builder, $name)
    {
        $builder->addOffsetX(0, $name, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addEmail(FlatbufferBuilder $builder, $email)
    {
        $builder->addOffsetX(1, $email, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addPassword(FlatbufferBuilder $builder, $password)
    {
        $builder->addOffsetX(2, $password, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endSetupRequest(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // name
        $builder->required($o, 6);  // email
        $builder->required($o, 8);  // password
        return $o;
    }
}
