<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace API\Fbs\Token;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatbufferBuilder;

class TokenRole extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return TokenRole
     */
    public static function getRootAsTokenRole(ByteBuffer $bb)
    {
        $obj = new TokenRole();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return TokenRole
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getId(): ?string
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getName(): ?string
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param int offset
     * @return string
     */
    public function getPermissions($j)
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($this->__vector($o) + $j * 4) : 0;
    }

    /**
     * @return int
     */
    public function getPermissionsLength()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return void
     */
    public static function startTokenRole(FlatbufferBuilder $builder)
    {
        $builder->StartObject(3);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int
     */
    public static function createTokenRole(FlatbufferBuilder $builder, $id, $name, $permissions)
    {
        $builder->startObject(3);
        self::addId($builder, $id);
        self::addName($builder, $name);
        self::addPermissions($builder, $permissions);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addId(FlatbufferBuilder $builder, $id)
    {
        $builder->addOffsetX(0, $id, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatbufferBuilder $builder, $name)
    {
        $builder->addOffsetX(1, $name, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addPermissions(FlatbufferBuilder $builder, $permissions)
    {
        $builder->addOffsetX(2, $permissions, 0);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createPermissionsVector(FlatbufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatbufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startPermissionsVector(FlatbufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatbufferBuilder $builder
     * @return int table offset
     */
    public static function endTokenRole(FlatbufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
